// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0J5Als5EZCAppD_L75de2vCeHdKuZytU',
    appId: '1:782651458004:web:1ef024d45ccd3bfbe55641',
    messagingSenderId: '782651458004',
    projectId: 'tender-341bc',
    authDomain: 'tender-341bc.firebaseapp.com',
    storageBucket: 'tender-341bc.appspot.com',
    measurementId: 'G-QJSKZDSMLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDnzA6_H2vG0FQccI9XkzJCh9mUQJ1Do',
    appId: '1:782651458004:android:fae0f455ec1c78c6e55641',
    messagingSenderId: '782651458004',
    projectId: 'tender-341bc',
    storageBucket: 'tender-341bc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0J5Als5EZCAppD_L75de2vCeHdKuZytU',
    appId: '1:782651458004:web:29e8e814ba88e80ee55641',
    messagingSenderId: '782651458004',
    projectId: 'tender-341bc',
    authDomain: 'tender-341bc.firebaseapp.com',
    storageBucket: 'tender-341bc.appspot.com',
    measurementId: 'G-F7F1TQMNR0',
  );
}
